import os
import sys

BIN_DIR=os.environ['BIN_DIR'];
GTEST_ROOT=os.environ['GTEST_ROOT'];

env=DefaultEnvironment().Clone();

SOURCES = [
 os.path.join(GTEST_ROOT, 'src/gtest-all.cc'),
] + Glob('*.cc') + Glob('*.c') + Glob('**/*.c')

env.Program(os.path.join(BIN_DIR, 'runTest'), SOURCES);


